### ISSUE TITLE
Save preditcion on .obj / .fbx formats

### ISSUE THREAD

**Issue by oljikeboost** [akashsengupta1997/HierarchicalProbabilistic3DHuman#2]
Hi! Thanks for your work. How can I save the output prediction of the body on .obj / .fbx formats?

**Comment by akashsengupta1997** [comment]
Hi, the output vertex mesh can be saved as a .obj file using the following short function:
```
def save_mesh_as_obj(out_path, vertices, faces):
    """
    Saves vertex mesh as obj file.
    :param out_path: path to save obj file.
    :param vertices: (num vertices, 3) numpy array of 3D vertices
    :param faces: (num faces, 3) numpy array, each row contains ordered
    indices of vertices belonging to that face.
    """
    with open(out_path, 'w') as fp:
        for v in vertices:
            fp.write('v %f %f %f\n' % (v[0], v[1], v[2]))
        if not(faces is None):
            for f in faces + 1:
                fp.write('f %d %d %d\n' % (f[0], f[1], f[2]))
```

or you can use trimesh's export function - see details here https://files.is.tue.mpg.de/black/talks/SMPL-made-simple-FAQs.pdf 

You may also consider saving the mesh in the .ply file format, since you can additionally save per-vertex variance as a per-vertex property (or "colour" using some colour map), if this is desired. (I guess this is possible with .obj too, but I am not super knowledgeable about this).

**Comment by AhmadNashaat0** [comment]
how to extract faces and vertices from smpl

**Comment by AhmadNashaat0** [comment]
how to extract faces and vertices from smpl
