### ISSUE TITLE
Why learn scale?

### ISSUE THREAD

**Issue by kristijanbartol** [akashsengupta1997/HierarchicalProbabilistic3DHuman#4]
Dear Akash,

I read your [paper](https://openaccess.thecvf.com/content/ICCV2021/papers/Sengupta_Hierarchical_Kinematic_Probability_Distributions_for_3D_Human_Shape_and_Pose_ICCV_2021_paper.pdf), as well as other papers from the series ([[2]](https://openaccess.thecvf.com/content/CVPR2021/papers/Sengupta_Probabilistic_3D_Human_Shape_and_Pose_Estimation_From_Multiple_Unconstrained_CVPR_2021_paper.pdf), [[3]](https://arxiv.org/pdf/2009.10013.pdf), [[4]](https://arxiv.org/pdf/2111.15404.pdf)). :) It's interesting that your attempts are one of the few trying to recover an accurate shape of the person, instead of mostly focusing on a 3D pose.

However, the crucial question that is still bothering me is why do you use unnormalized loss components, such verts3d and joints3d? I guess you already thought about that and decided to still force the model to learn the scale. The advantage that I see using this approach is the regularization effect, where you confuse the model and then hope that it will still manage to somehow figure out the scale, i.e., height of the person.

Thanks in advance!

**Comment by akashsengupta1997** [comment]
Hi Kristijan - thanks for your interest in our work! (and sorry for the late response.)

Actually in an updated version of this work, we no longer apply verts3D and joints3D losses :) Empirically, for this ICCV2021 publication, we found that they improved our pose metrics (MPJPE) slightly, so they were included to prevent us from being too far behind the SOTA for pose estimation. However, we have re-visited the method and concluded that they are no longer necessary (or even detrimental) when doing probabilistic shape and pose estimation, since these deterministic verts/joints3D losses are at loggerheads with the probabilistic log-likelihood losses on shape and pose parameters. (Hopefully we will be able to show this in a future publication :) )

Nevertheless, applying a log-likelihood loss on shape parameters is technically still "unnormalised" since the shape parameters encode scale. We figured that it is very difficult (if not impossible) to accurately estimate scale from a single-image without any sort of camera calibration. In a real use case, we would ask users to input their ground-truth height, and scale our "relative" predictions using their height to obtain "absolute" body shape/measurements.

Of course the main reason why estimating scale is hard is because it is an ambiguous problem --> a small person standing close to the camera and a large person standing farther away will project to a similar size on the 2D image plane**. We hope to produce a shape parameter estimate + a camera location estimate that jointly ensure that the projected body mesh matches the size of the subject in the image plane.

Perhaps a better approach would be to predict a joint distribution over both shape parameters AND camera parameters. Then, this joint distribution may model this correlation between 3D shape, camera location and size in the 2D image plane.

I would be interested to hear your thoughts on scale-normalised losses :) 

**Assuming they have similar limb proportions, which may not be a valid assumption depending on correlations between limb proportions and height.

**Comment by akashsengupta1997** [comment]
Hi Kristijan,

Sorry for the super late response!

I believe I tried early on in this project (i.e. a couple of years ago now!) to use normalised joints3D loss, but did not find much improvement in the network, so did not try again. However, since then my experimental set-up has changed and improved, so it is certainly possible that a normalised loss would be helpful, and that my previous conclusions were inaccurate! I will try applying normalised losses again, hopefully soon-ish, and see how it goes.

(Just noticed your PS that you have already tried to use the normalised losses but did not find much improvement - there may be something we are missing)

Also I did not abandon the verts3D and joints3D losses due to the normalisation, but because they are not probabilistic losses. To make them probabilistic, one would need to apply a log-likelihood loss on verts3D and joints3D (considering that the GT verts3D and joints3D are only one possible explanation of the input image), which would require converting the probability distribution over SMPL parameters into a probability distribution over verts3D and joints3D - I do not believe this is a simple task!

**Comment by AhmedTooHere** [comment]
Hi guys!
@akashsengupta1997 you said:  In a real use case, we would ask users to input their ground-truth height, and scale our "relative" predictions using their height to obtain "absolute" body shape/measurements.

Im also trying to a see the estimation of body shape/measurements with the height of the person as an input and compare using your approach. Can you please indicate me a path on how we can perform the scale of the predicitions giving a height as an input ? Thanks in advance.
